### ISSUE TITLE
Wearでアプリが起動しない

### ISSUE THREAD

**Issue by hotuta** [JAG-SC/ABC2016SpringClient#17]
先ほど実機テストをしたところ問題が発生したため終了しますとなりアプリが起動しない状態です。
一応、ログを載せておきます。

```
02-22 23:35:03.322 20854-20854/jagsc.org.abc2016springclient I/Process: Sending signal. PID: 20854 SIG: 9
02-22 23:35:09.736 20914-20914/jagsc.org.abc2016springclient D/AndroidRuntime: Shutting down VM
02-22 23:35:09.737 20914-20914/jagsc.org.abc2016springclient E/AndroidRuntime: FATAL EXCEPTION: main
                                                                               Process: jagsc.org.abc2016springclient, PID: 20914
                                                                               java.lang.RuntimeException: Unable to start activity ComponentInfo{jagsc.org.abc2016springclient/jagsc.org.abc2016springclient.MainActivity}: java.lang.ClassCastException: android.app.Application cannot be cast to jagsc.org.abc2016springclient.GlobalVariables
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
                                                                                   at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                   at android.os.Looper.loop(Looper.java:135)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                                                                                Caused by: java.lang.ClassCastException: android.app.Application cannot be cast to jagsc.org.abc2016springclient.GlobalVariables
                                                                                   at jagsc.org.abc2016springclient.MainActivity.onCreate(MainActivity.java:50)
                                                                                   at android.app.Activity.performCreate(Activity.java:5990)
                                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
                                                                                   at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                   at android.os.Looper.loop(Looper.java:135) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                                   at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
02-22 23:35:18.648 20968-20968/jagsc.org.abc2016springclient I/Process: Sending signal. PID: 20968 SIG: 9

```

**Comment by prprhyt** [comment]
修正したものをプルリク投げておきました

**Comment by hotuta** [comment]
さきほど実機テストし正常に動きました!
ご対応ありがとうございました。

WearとHandheldのアプリが起動しない問題を修正 by prprhyt · Pull Request #18 · JAG-SC/ABC2016SpringClient
https://github.com/JAG-SC/ABC2016SpringClient/pull/18
