### ISSUE TITLE
Wearでアプリが起動しない(Yuki014君のリポジトリにて)

### ISSUE THREAD

**Issue by hotuta** [JAG-SC/ABC2016SpringClient#26]
https://github.com/Yuki014/ABC2016SpringClient
実機テストをしてみたところ、"問題が発生したため終了します"となりアプリが起動しない状態です。
一応、ログを載せておきます。

```
02-28 12:39:12.109 4471-4471/jagsc.org.abc2016springclient E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             Process: jagsc.org.abc2016springclient, PID: 4471
                                                                             java.lang.RuntimeException: Unable to start activity ComponentInfo{jagsc.org.abc2016springclient/jagsc.org.abc2016springclient.MainActivity}: java.lang.ClassCastException: android.app.Application cannot be cast to jagsc.org.abc2016springclient.GlobalVariables
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
                                                                                 at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                 at android.os.Looper.loop(Looper.java:135)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                                                                              Caused by: java.lang.ClassCastException: android.app.Application cannot be cast to jagsc.org.abc2016springclient.GlobalVariables
                                                                                 at jagsc.org.abc2016springclient.MainActivity.onCreate(MainActivity.java:59)
                                                                                 at android.app.Activity.performCreate(Activity.java:5990)
                                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
                                                                                 at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                 at android.os.Looper.loop(Looper.java:135) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                                 at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
```

**Comment by Yuki014** [comment]
今上がっているのは昨夜一気にmargeした影響で様々な場所にバグがあるので今しっかりとした流れに修正中です
今しばらくお待ち下さい

**Comment by hotuta** [comment]
了解です。
